# Generated by Django 3.1.7 on 2021-03-12 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Wprowadz nazwisko autora', max_length=100, verbose_name='Nazwisko autora')),
                ('names', models.CharField(help_text='Wprowadz imiona autora (bez dodatkowych znakow pomiedzy)', max_length=200, verbose_name='Imiona autora')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('summary', models.TextField(help_text='Wprowadz krotki opis ksiazki', max_length=1000, verbose_name='Opis książki')),
                ('isbn', models.IntegerField(help_text='13 znakowy <a href="https://www.isbn-international.org/content/what-isbn">numer ISBN</a>, wyłącznie cyfry', verbose_name='ISBN')),
                ('first_published', models.IntegerField(help_text='Wprowadz rok pierwszego oryginalnego wydania, z "-", jeśli p.n.e.', verbose_name='Data pierwszego wydania')),
                ('author', models.ManyToManyField(help_text='Wybierz autora lub autorow ksiazki.', to='catalog.Author', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wprowadz gatunek ksiazki (np."Romans")', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wprowadz jezyk ksiazki (np. "polski")', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalne ID dla kazdej ksiazki w calej księgarni.', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Wypożyczona do')),
                ('status', models.CharField(blank=True, choices=[('m', 'W trakcie renowacji'), ('o', 'Wypożyczona'), ('a', 'Dostępna'), ('r', 'Zarezerwowana')], default='a', help_text='Dostepnosc ksiazki', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book', verbose_name='Tytuł książki')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pożyczający')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Wybierz gatunek ksiazki.', to='catalog.Genre', verbose_name='Gatunek'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=0, help_text='Wybierz jezyk ksiazki.', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.language', verbose_name='Język'),
        ),
    ]
