# Generated by Django 3.1.7 on 2021-03-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, help_text='Wybierz jezyk ksiazki.', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.language', verbose_name='Język'),
        ),
    ]
