# Generated by Django 3.1.7 on 2021-03-15 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(help_text='13 znakowy <a href="https://www.isbn-international.org/content/what-isbn">numer ISBN</a>, wyłącznie cyfry', validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)], verbose_name='ISBN'),
        ),
    ]
