# Generated by Django 3.1.7 on 2021-03-15 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210315_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_published',
            field=models.IntegerField(help_text='Wprowadz rok pierwszego oryginalnego wydania, z "-", jeśli p.n.e.', validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='Data pierwszego wydania'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(help_text='13 znakowy <a href="https://www.isbn-international.org/content/what-isbn">numer ISBN</a>, wyłącznie cyfry', validators=[django.core.validators.MinValueValidator(1000000000000), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN'),
        ),
    ]
