# Generated by Django 3.1.7 on 2021-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210317_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, help_text='Wprowadz krotki zyciorys i charakterystyke autora', max_length=300, null=True, verbose_name='Opis autora'),
        ),
    ]
