# Generated by Django 3.1.7 on 2021-03-24 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Wprowadz date urodzin autora  w formacie RRRR-MM-DD', null=True, verbose_name='Data urodzin'),
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Wprowadz date smierci autora w formacie RRRR-MM-DD', null=True, verbose_name='Data śmierci'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Wprowadz krotki zyciorys i charakterystyke autora', null=True, verbose_name='Notka biograficzna'),
        ),
        migrations.AlterField(
            model_name='author',
            name='names',
            field=models.CharField(help_text='Wprowadz imiona autora (bez dodatkowych znakow pomiedzy)', max_length=200, verbose_name='Imiona'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(help_text='Wprowadz nazwisko autora', max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_published',
            field=models.IntegerField(help_text='Wprowadz rok pierwszego oryginalnego wydania, z "-", jeśli p.n.e.', validators=[django.core.validators.MaxValueValidator(limit_value=2021, message='Rok nie moze byc pozniejszy od biezacego.')], verbose_name='Rok pierwszego wydania'),
        ),
    ]
