# Generated by Django 3.1.7 on 2021-05-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_bookinstance_prolonged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname'], 'permissions': (('can_edit_author', 'Can edit an author'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Can edit a book'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Can set a book as returned'),)},
        ),
    ]
