# Generated by Django 3.1.7 on 2021-05-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210501_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'W trakcie renowacji'), ('o', 'Wypożyczona'), ('a', 'Dostępna'), ('r', 'Zarezerwowana')], default='a', max_length=1, verbose_name='Dostępność książki'),
        ),
    ]
