# Generated by Django 3.1.7 on 2021-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20210502_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('m', 'W trakcie renowacji'), ('o', 'Wypożyczona'), ('a', 'Dostępna'), ('r', 'Zarezerwowana')], default='a', max_length=1, verbose_name='Dostępność książki'),
        ),
    ]
